language: go

env:
    - GO15VENDOREXPERIMENT=1

os:
    - linux
    - osx

go:
    - 1.6.3
    - 1.5.4
    - tip

script:
    - make
    - make gotest

before_install:
    - mkdir -p ../../CodisLabs
    - ln -s `pwd` ../../CodisLabs/codis
